/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UICoordinator;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import model.EEmployeeRol;
import model.Employee;

/**
 *
 * @author Ximena
 */
public class FrTemplate extends javax.swing.JFrame {
    private Employee employee; 

    public JTextArea getTxtconsider() {
        return txtconsider;
    }

    public void setTxtconsider(JTextArea txtconsider) {
        this.txtconsider = txtconsider;
    }

    public JTextArea getTxtintro() {
        return txtintro;
    }

    public void setTxtintro(JTextArea txtintro) {
        this.txtintro = txtintro;
    }

    public JTextArea getTxtresolve() {
        return txtresolve;
    }

    public void setTxtresolve(JTextArea txtresolve) {
        this.txtresolve = txtresolve;
    }

    public JTextArea getTxtresult() {
        return txtresult;
    }

    public void setTxtresult(JTextArea txtresult) {
        this.txtresult = txtresult;
    }
    private UICoordinator ui;
    
    /**
     * Creates new form FrTemplate
     */
    public FrTemplate() {
        ui=new UICoordinator();
        initComponents();
        this.setResizable(false);
        ui.selectTemplates(this);
        
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    public void setMenu(){
   
        
        if(employee.getRol() == EEmployeeRol.ASSINTANT){
            btnNewTemplate.setEnabled(false);
            btnViewRequest.setEnabled(true);
            btnViewResolution.setEnabled(true);
            btnviewStadistics.setEnabled(false);
        }
        else if (employee.getRol() == EEmployeeRol.CORDINATOR){
            btnNewTemplate.setEnabled(true);
            btnViewRequest.setEnabled(true);
            btnViewResolution.setEnabled(true);
            btnviewStadistics.setEnabled(true);
        }
        else if(employee.getRol() == EEmployeeRol.HEADMASTER){
            btnNewTemplate.setEnabled(false);
            btnViewRequest.setEnabled(false);
            btnViewResolution.setEnabled(false); 
            btnviewStadistics.setEnabled(true);
        }
        else if(employee.getRol() == EEmployeeRol.PROFESSOR){
            btnNewTemplate.setEnabled(false);
            btnViewRequest.setEnabled(false);
            btnViewResolution.setEnabled(false);
            btnviewStadistics.setEnabled(false);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbparamintro = new javax.swing.JComboBox<>();
        btnparamintro = new javax.swing.JButton();
        btnparamresult = new javax.swing.JButton();
        cbparamresult = new javax.swing.JComboBox<>();
        btnparamconsider = new javax.swing.JButton();
        cbparamconsider = new javax.swing.JComboBox<>();
        cbparamresolve = new javax.swing.JComboBox<>();
        btnparamresolve = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtintro = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtresult = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtconsider = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtresolve = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cbtemplate = new javax.swing.JComboBox<>();
        cbnumtemplate = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnNewTemplate = new javax.swing.JMenuItem();
        btnCurrentTemplate = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnViewRequest = new javax.swing.JMenuItem();
        btnviewStadistics = new javax.swing.JMenuItem();
        btnViewResolution = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn.setBackground(new java.awt.Color(1, 55, 119));
        pn.setPreferredSize(new java.awt.Dimension(1070, 1100));
        pn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Introducción ");
        pn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Resultado Único");
        pn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 307, -1, 20));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Considerandos");
        pn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Resuelvo");
        pn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, -1, -1));

        cbparamintro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Nombre Director", "Nombre del Estudiante", "Carné del Estudiante", "Código del Curso", "Nombre del Curso", "Número de Grupo", "Profesor", "Periodo", "Año", "Semestre" }));
        pn.add(cbparamintro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 140, 30));

        btnparamintro.setBackground(new java.awt.Color(239, 62, 53));
        btnparamintro.setForeground(new java.awt.Color(254, 254, 254));
        btnparamintro.setText("Insertar");
        btnparamintro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparamintroActionPerformed(evt);
            }
        });
        pn.add(btnparamintro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, -1, -1));

        btnparamresult.setBackground(new java.awt.Color(239, 62, 53));
        btnparamresult.setForeground(new java.awt.Color(254, 254, 254));
        btnparamresult.setText("Insertar");
        btnparamresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparamresultActionPerformed(evt);
            }
        });
        pn.add(btnparamresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, -1, -1));

        cbparamresult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Nombre Director", "Nombre del Estudiante", "Carné del Estudiante", "Código del Curso", "Nombre del Curso", "Número de Grupo", "Profesor", "Periodo", "Año", "Semestre" }));
        pn.add(cbparamresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 140, 30));

        btnparamconsider.setBackground(new java.awt.Color(239, 62, 53));
        btnparamconsider.setForeground(new java.awt.Color(254, 254, 254));
        btnparamconsider.setText("Insertar");
        btnparamconsider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparamconsiderActionPerformed(evt);
            }
        });
        pn.add(btnparamconsider, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, -1, -1));

        cbparamconsider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Nombre Director", "Nombre del Estudiante", "Carné del Estudiante", "Código del Curso", "Nombre del Curso", "Número de Grupo", "Profesor", "Periodo", "Año", "Semestre" }));
        pn.add(cbparamconsider, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 140, -1));

        cbparamresolve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Nombre Director", "Nombre del Estudiante", "Carné del Estudiante", "Código del Curso", "Nombre del Curso", "Número de Grupo", "Profesor", "Periodo", "Año", "Semestre" }));
        pn.add(cbparamresolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 140, -1));

        btnparamresolve.setBackground(new java.awt.Color(239, 62, 53));
        btnparamresolve.setForeground(new java.awt.Color(254, 254, 254));
        btnparamresolve.setText("Insertar");
        btnparamresolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparamresolveActionPerformed(evt);
            }
        });
        pn.add(btnparamresolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 680, -1, -1));

        txtintro.setColumns(20);
        txtintro.setRows(5);
        jScrollPane8.setViewportView(txtintro);

        pn.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1020, 150));

        txtresult.setColumns(20);
        txtresult.setRows(5);
        jScrollPane9.setViewportView(txtresult);

        pn.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 1020, 138));

        txtconsider.setColumns(20);
        txtconsider.setRows(5);
        jScrollPane10.setViewportView(txtconsider);

        pn.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 1020, 138));

        txtresolve.setColumns(20);
        txtresolve.setRows(5);
        jScrollPane11.setViewportView(txtresolve);

        pn.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 1020, 138));

        jButton1.setBackground(new java.awt.Color(239, 62, 53));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pn.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        cbtemplate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inclusión", "Exclusión", "Error de Nota" }));
        cbtemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtemplateActionPerformed(evt);
            }
        });
        pn.add(cbtemplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 30));

        pn.add(cbnumtemplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 60, 30));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Tipo de Plantilla");
        pn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, -1));

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Número");
        pn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Seleccione su Plantilla");
        pn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jScrollPane1.setViewportView(pn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        jMenu3.setText("Archivo");

        btnNewTemplate.setText("Nueva Plantilla...");
        btnNewTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTemplateActionPerformed(evt);
            }
        });
        jMenu3.add(btnNewTemplate);

        btnCurrentTemplate.setText("Seleccionar Plantilla Actual...");
        btnCurrentTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentTemplateActionPerformed(evt);
            }
        });
        jMenu3.add(btnCurrentTemplate);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Ver ");

        btnViewRequest.setText("Ver Solicitudes");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });
        jMenu4.add(btnViewRequest);

        btnviewStadistics.setText("Ver Estadísticas");
        btnviewStadistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewStadisticsActionPerformed(evt);
            }
        });
        jMenu4.add(btnviewStadistics);

        btnViewResolution.setText("Ver Resoluciones");
        btnViewResolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResolutionActionPerformed(evt);
            }
        });
        jMenu4.add(btnViewResolution);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getCbnumtemplate() {
        return cbnumtemplate;
    }

    public void setCbnumtemplate(JComboBox<String> cbnumtemplate) {
        this.cbnumtemplate = cbnumtemplate;
    }

    public JComboBox<String> getCbtemplate() {
        return cbtemplate;
    }

    public void setCbtemplate(JComboBox<String> cbtemplate) {
        this.cbtemplate = cbtemplate;
    }

    private void btnNewTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTemplateActionPerformed
        // TODO add your handling code here:
        NewTemplate fr=new NewTemplate();
        fr.setEmployee(employee); 
        fr.setMenu(); 
        fr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNewTemplateActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        FrViewRequest fvr=new FrViewRequest();
        fvr.setEmployee(employee); 
        fvr.setMenu(); 
        fvr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnviewStadisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewStadisticsActionPerformed
        // TODO add your handling code here:
        FrStadistics frstadistics= new FrStadistics();
        frstadistics.setEmployee(employee);
        frstadistics.setMenu();
        frstadistics.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnviewStadisticsActionPerformed

    private void btnViewResolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResolutionActionPerformed
        // TODO add your handling code here:
        FrResolution frResolution= new FrResolution();
        frResolution.setEmployee(employee);
        frResolution.setMenu();
        frResolution.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewResolutionActionPerformed

    private void btnparamintroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparamintroActionPerformed
        // TODO add your handling code here:
        ui.insertParam(txtintro, cbparamintro.getSelectedIndex());
        
    }//GEN-LAST:event_btnparamintroActionPerformed

    private void btnparamresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparamresultActionPerformed
        // TODO add your handling code here:
         ui.insertParam(txtresult, cbparamresult.getSelectedIndex());
    }//GEN-LAST:event_btnparamresultActionPerformed

    private void btnparamconsiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparamconsiderActionPerformed
        // TODO add your handling code here:
         ui.insertParam(txtconsider, cbparamconsider.getSelectedIndex());
    }//GEN-LAST:event_btnparamconsiderActionPerformed

    private void btnparamresolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparamresolveActionPerformed
        // TODO add your handling code here:
         ui.insertParam(txtresolve, cbparamresolve.getSelectedIndex());
    }//GEN-LAST:event_btnparamresolveActionPerformed

    private void cbtemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtemplateActionPerformed
        // TODO add your handling code here:
        ui.selectTemplates(this);
    }//GEN-LAST:event_cbtemplateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ui.getTemplate(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCurrentTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentTemplateActionPerformed
        // TODO add your handling code here:
        FrResolution fr=new FrResolution(true, Integer.parseInt(cbnumtemplate.getSelectedItem().toString()), cbtemplate.getSelectedIndex());
        fr.setVisible(true);
        fr.setEmployee(employee);
        fr.setMenu();
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCurrentTemplateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTemplate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCurrentTemplate;
    private javax.swing.JMenuItem btnNewTemplate;
    private javax.swing.JMenuItem btnViewRequest;
    private javax.swing.JMenuItem btnViewResolution;
    private javax.swing.JButton btnparamconsider;
    private javax.swing.JButton btnparamintro;
    private javax.swing.JButton btnparamresolve;
    private javax.swing.JButton btnparamresult;
    private javax.swing.JMenuItem btnviewStadistics;
    private javax.swing.JComboBox<String> cbnumtemplate;
    private javax.swing.JComboBox<String> cbparamconsider;
    private javax.swing.JComboBox<String> cbparamintro;
    private javax.swing.JComboBox<String> cbparamresolve;
    private javax.swing.JComboBox<String> cbparamresult;
    private javax.swing.JComboBox<String> cbtemplate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pn;
    private javax.swing.JTextArea txtconsider;
    private javax.swing.JTextArea txtintro;
    private javax.swing.JTextArea txtresolve;
    private javax.swing.JTextArea txtresult;
    // End of variables declaration//GEN-END:variables
}
